# Generated by Django 4.1.7 on 2023-04-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('menu_name', models.CharField(max_length=25)),
                ('order', models.IntegerField(default=0, unique=True)),
                ('depth', models.IntegerField(default=0)),
            ],
        ),
    ]
